### ISSUE TITLE
Decide on language

### ISSUE THREAD

**Issue by martindilling** [collabexperiment/platform#1]
Let's decide on what language we are working with

**Comment by martindilling** [comment]
Just to start out, I'm thinking PHP.
Easy to set up, easy to run and easy to deploy ;)

**Comment by JessNielsen** [comment]
Yes and most of us have experience in it. We should be able to expedite the developement.
If we were to use it we might however need another discussion on version of the language and whether to use stuff as hvvm to make up for some of the disadvantages of php's lack of precompilation.

**Comment by martindilling** [comment]
To keep it easy to use and help out here I'd say plain php, the latest stable version. Can't come up with any good argument why we should use an older version ;)

**Comment by Munk91** [comment]
Doesn't it depend on which type of application we want to make? What about an app or something, would that be relevant? Or is it implicit that it is a web application?
If so, PHP as some kind of API to a frontend app like Angular would be awesome.

**Comment by martindilling** [comment]
From conversations on facebook it looks like we have decided on php, so I'm gonna close this ;)

If anyone have any objections it's now you should comment ;)
