### ISSUE TITLE
Decide on framework

### ISSUE THREAD

**Issue by martindilling** [collabexperiment/platform#2]
Let's decide on that framework we should use if any

Depends on #1

**Comment by frederikspang** [comment]
I'm thinking laravel server, if we end up with php. Or Rails if not?

**Comment by martindilling** [comment]
I'm definitely most on the php laravel wagon ;)

**Comment by JessNielsen** [comment]
Me too. The laravel family is where my skills are based.

**Comment by Munk91** [comment]
I'm voting for Lumen (Laravel's micro framework). We will then have more space for customization, and aren't bound to the all the stuff Laravel provides. We can easily apply stuff to Lumen which isn't included compared to Laravel. (eg. Eloquent, etc.)

**Comment by martindilling** [comment]
I can't see the benefit in using Lumen instead of Laravel. As I see it Laravel has the same possibilities for customization, but more guidelines out of the box which I can only see as an advantage when we're trying to create a project with a lot of collaborators :)
And the size goals for this also makes me think there is more advantage in using the full framework instead of a micro framework.

That said, I'm happy to be proven wrong, this is just my thoughts ;)

**Comment by Munk91** [comment]
One of the main benefits is performance, a Lumen project simply runs alot faster. My experience is that there are too many unused classes in Laravels Framework. But again, it is just my opinion, it's not that I don't want to use Laravel.
The good thing about starting in Lumen is that you can change it to a Laravel project whenever it is needed, it is also simple the other way around, but not always possible in a glimpse.
But your point about alot of collaborators makes perfect sense, indeed.

**Comment by martindilling** [comment]
I'm really not so sure about performance in Lumen, yea the number look good, but they are based on a run where everything is disabled. And we would probably end up enabling most of the things anyway ;)

With many people at different levels (no clue if that's the case, just taking that into account in the decision) I think it's easier to jump in and follow the "Laravel way" rather than we in collaboration are creating a way to follow :)

**Comment by JessNielsen** [comment]
Actually i think that lumen would be a good solution. The two of them are not that far apart in terms of codebase, and beginners have just as easy a time learning lumen as laravel. with lumen we get the added benefit of not having to use blade and just having it as an api to use with a client somewhere.

**Comment by martindilling** [comment]
Is it a benefit to serve an api and build a separate client instead of using blade? Sounds like a lot of added work with little benefit? ;)

**Comment by Munk91** [comment]
Well, is actually depends on which kind of system we want to build. Let's start with Laravel, it's not a big deal. But I'm still quite sure Lumen is a better idea though.

**Comment by martindilling** [comment]
What are people thinking we are building? An api and a separate client or a "simple" web app?

My thought was a "simple" web app, using a php template language.

**Comment by Munk91** [comment]
Could close this issue, since it's been decided to use Laravel.
@martindilling
